export const DUMMY_DATA = [
  {
    id: 1,
    first_name: "Alfie",
    last_name: "MacDiarmid",
    email: "amacdiarmid0@cafepress.com",
    gender: "Non-binary",
    occupation: "Safety Technician III",
    photoURL: "https://robohash.org/corruptiquidemet.png?size=300x300&set=set1",
    age: 18,
  },
  {
    id: 2,
    first_name: "Park",
    last_name: "Braybrookes",
    email: "pbraybrookes1@linkedin.com",
    gender: "Male",
    occupation: "Statistician II",
    photoURL:
      "https://robohash.org/aliassimiliquedeserunt.png?size=300x300&set=set1",
    age: 20,
  },
  {
    id: 3,
    first_name: "Denys",
    last_name: "Collins",
    email: "dcollins2@bigcartel.com",
    gender: "Male",
    occupation: "Mechanical Systems Engineer",
    photoURL:
      "https://robohash.org/velitrecusandaeautem.png?size=300x300&set=set1",
    age: 19,
  },
  {
    id: 4,
    first_name: "Duffy",
    last_name: "Gaywood",
    email: "dgaywood3@time.com",
    gender: "Male",
    occupation: "Tax Accountant",
    photoURL:
      "https://robohash.org/natusvoluptasatque.png?size=300x300&set=set1",
    age: 18,
  },
  {
    id: 5,
    first_name: "Nertie",
    last_name: "Croal",
    email: "ncroal4@nydailynews.com",
    gender: "Female",
    occupation: "Tax Accountant",
    photoURL: "https://robohash.org/iustooccaecatiet.png?size=300x300&set=set1",
    age: 78,
  },
  {
    id: 6,
    first_name: "Marita",
    last_name: "McMorland",
    email: "mmcmorland5@dion.ne.jp",
    gender: "Female",
    occupation: "Structural Engineer",
    photoURL:
      "https://robohash.org/autnullaaccusantium.png?size=300x300&set=set1",
    age: 66,
  },
  {
    id: 7,
    first_name: "Teodoor",
    last_name: "Edler",
    email: "tedler6@gmpg.org",
    gender: "Male",
    occupation: "Senior Editor",
    photoURL: "https://robohash.org/utquiablanditiis.png?size=300x300&set=set1",
    age: 23,
  },
  {
    id: 8,
    first_name: "Francyne",
    last_name: "Beamish",
    email: "fbeamish7@e-recht24.de",
    gender: "Female",
    occupation: "Staff Accountant I",
    photoURL:
      "https://robohash.org/cupiditateinventorevoluptatibus.png?size=300x300&set=set1",
    age: 73,
  },
];
